dependencies = []
description = "Define a custom handler and router based on gorilla + negroni with easy integration of middlewares"
flags = ["lib"]
languages = ["go", "github-actions"]
owner = "team-infrastructure-services@scalingo.com"
team = "IST"
tier = 1
version = "1.1.0"
