dependencies = []
description = "Define a custom handler and router based on gorilla + negroni with easy integration of middlewares"
flags = ["lib"]
languages = ["go"]
owner = "etienne@scalingo.com"
team = "IST"
version = "1.1.0"
